// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj5YXCgspipnCGpPomwnIfcTYLvT_e-9g',
    appId: '1:3995571154:web:cc91f4b2780a5a40b5ee0b',
    messagingSenderId: '3995571154',
    projectId: 'cce106-crud',
    authDomain: 'cce106-crud.firebaseapp.com',
    storageBucket: 'cce106-crud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV8iDU2vqGfqg17BAA4KLgeZHQTSS_7UE',
    appId: '1:3995571154:android:b84e5c30f0b901f1b5ee0b',
    messagingSenderId: '3995571154',
    projectId: 'cce106-crud',
    storageBucket: 'cce106-crud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGeQEcam9kbg5ImhA1s1_a1Exbx0HX98',
    appId: '1:3995571154:ios:8f4c7a1ab2c17736b5ee0b',
    messagingSenderId: '3995571154',
    projectId: 'cce106-crud',
    storageBucket: 'cce106-crud.firebasestorage.app',
    iosBundleId: 'com.example.activity6',
  );
}
